// <auto-generated />
using System;
using EmergencyAlerts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmergencyAlerts.Infrastructure.Migrations
{
    [DbContext(typeof(EmergencyAlertsDbContext))]
    partial class EmergencyAlertsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmergencyAlerts.Domain.Entities.AdminBoundary", b =>
                {
                    b.Property<Guid>("BoundaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("boundary_id");

                    b.Property<int>("AdminLevel")
                        .HasColumnType("integer")
                        .HasColumnName("admin_level");

                    b.Property<string>("BoundaryPolygonWkt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("boundary_polygon_wkt");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("region_code");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("region_name");

                    b.HasKey("BoundaryId");

                    b.HasIndex("RegionCode")
                        .IsUnique();

                    b.ToTable("admin_boundaries", "emergency_alerts");
                });

            modelBuilder.Entity("EmergencyAlerts.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("delivery_status");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("headline");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("en-GB")
                        .HasColumnName("language_code");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PendingApproval")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("AlertId");

                    b.HasIndex("DeliveryStatus")
                        .HasFilter("delivery_status = 'Pending'");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.ToTable("alerts", "emergency_alerts");
                });

            modelBuilder.Entity("EmergencyAlerts.Domain.Entities.ApprovalRecord", b =>
                {
                    b.Property<Guid>("ApprovalId")
                        .HasColumnType("uuid")
                        .HasColumnName("approval_id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("approver_id");

                    b.Property<DateTime>("DecidedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.HasKey("ApprovalId");

                    b.HasIndex("AlertId")
                        .IsUnique();

                    b.ToTable("approval_records", "emergency_alerts");
                });

            modelBuilder.Entity("EmergencyAlerts.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<string>("AreaDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("area_description");

                    b.Property<string>("AreaPolygonWkt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("area_polygon_wkt");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("region_code");

                    b.HasKey("AreaId");

                    b.HasIndex("AlertId");

                    b.ToTable("areas", "emergency_alerts");
                });

            modelBuilder.Entity("EmergencyAlerts.Domain.Entities.CorrelationEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.PrimitiveCollection<Guid[]>("AlertIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("alert_ids");

                    b.Property<string>("ClusterSeverity")
                        .HasColumnType("text")
                        .HasColumnName("cluster_severity");

                    b.Property<DateTime>("DetectionTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("detection_timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("PatternType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern_type");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("region_code");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.HasKey("EventId");

                    b.HasIndex("DetectionTimestamp");

                    b.ToTable("correlation_events", "emergency_alerts");
                });

            modelBuilder.Entity("EmergencyAlerts.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<string>("AcsOperationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acs_operation_id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("attempted_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("AttemptId");

                    b.HasIndex("AlertId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("Status")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("delivery_attempts", "emergency_alerts");
                });

            modelBuilder.Entity("EmergencyAlerts.Domain.Entities.Recipient", b =>
                {
                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_address");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("RecipientId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("recipients", "emergency_alerts");
                });

            modelBuilder.Entity("EmergencyAlerts.Domain.Entities.ApprovalRecord", b =>
                {
                    b.HasOne("EmergencyAlerts.Domain.Entities.Alert", "Alert")
                        .WithOne("ApprovalRecord")
                        .HasForeignKey("EmergencyAlerts.Domain.Entities.ApprovalRecord", "AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("EmergencyAlerts.Domain.Entities.Area", b =>
                {
                    b.HasOne("EmergencyAlerts.Domain.Entities.Alert", "Alert")
                        .WithMany("Areas")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("EmergencyAlerts.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.HasOne("EmergencyAlerts.Domain.Entities.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmergencyAlerts.Domain.Entities.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("EmergencyAlerts.Domain.Entities.Alert", b =>
                {
                    b.Navigation("ApprovalRecord");

                    b.Navigation("Areas");
                });
#pragma warning restore 612, 618
        }
    }
}
