---
# Geographic correlation via COLLECT - pairs alerts in same region
apiVersion: v1
kind: ContinuousQuery
name: geo-correlation-v2
spec:
  mode: query
  sources:
    subscriptions:
      - id: postgres-alerts
        nodes:
          - sourceLabel: alerts
          - sourceLabel: areas
    joins:
      - id: ALERT_HAS_AREA
        keys:
          - label: alerts
            property: alert_id
          - label: areas
            property: alert_id
  query: |
    MATCH (a:alerts)-[:ALERT_HAS_AREA]->(area:areas)
    WHERE a.status IN ['Approved', 'PendingApproval']
      AND area.region_code IS NOT NULL
    WITH area.region_code AS regionCode, collect(a.alert_id) AS alertIds, count(a) AS alertCount
    WHERE alertCount >= 2
    RETURN
      regionCode AS regionCode,
      alertCount AS alertCount
