apiVersion: v1
kind: ContinuousQuery
name: geographic-correlation
spec:
  mode: query
  sources:
    subscriptions:
      - id: postgres-alerts
        nodes:
          - sourceLabel: alerts
          - sourceLabel: areas
    joins:
      - id: ALERT_HAS_AREA
        keys:
          - label: alerts
            property: alert_id
          - label: areas
            property: alert_id
  query: |
    MATCH (a:alerts)-[:ALERT_HAS_AREA]->(area:areas)
    WHERE a.status IN ['Approved', 'PendingApproval']
      AND area.region_code IS NOT NULL
    WITH area.region_code AS regionCode, count(a) AS alertCount
    WHERE alertCount >= 2
    RETURN regionCode, alertCount
